// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliticalPaths.Infrastructure.Persistence;

#nullable disable

namespace PoliticalPaths.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520163745_DomainModelSkeleton")]
    partial class DomainModelSkeleton
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PoliticalPaths.Domain.Candidacies.Candidacy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ElectoralCommitteeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ElectoralListId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ListPosition")
                        .HasColumnType("int");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Profile")
                        .HasColumnType("int");

                    b.Property<string>("SourceFingerprint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long?>("SourceImportRowId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectoralCommitteeId");

                    b.HasIndex("ElectoralDistrictId");

                    b.HasIndex("ElectoralListId");

                    b.HasIndex("SourceFingerprint")
                        .IsUnique();

                    b.HasIndex("PoliticianId", "ElectionId");

                    b.ToTable("Candidacies", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Candidacies.CandidacyVoteResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CandidacyId")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("Elected")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("PreferentialVotes")
                        .HasColumnType("int");

                    b.Property<long?>("SourceImportRowId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("VotePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("VotesReceived")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidacyId")
                        .IsUnique();

                    b.HasIndex("ElectoralDistrictId");

                    b.HasIndex("ElectionId", "ElectoralDistrictId");

                    b.ToTable("CandidacyVoteResults", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Chamber")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ElectionDate")
                        .HasColumnType("date");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid?>("LegislativeTermId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid?>("ParentLegislativeTermId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Profile")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReplacesMandateId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<Guid?>("VoivodeshipTerritorialUnitId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LegislativeTermId");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.HasIndex("ParentLegislativeTermId");

                    b.HasIndex("VoivodeshipTerritorialUnitId");

                    b.HasIndex("Year", "Chamber", "Scope");

                    b.ToTable("Elections", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralCommittee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.HasIndex("PartyId");

                    b.ToTable("ElectoralCommittees", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralDistrict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Chamber")
                        .HasColumnType("int");

                    b.Property<int>("DistrictNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.HasIndex("ElectionId", "Chamber", "DistrictNumber");

                    b.ToTable("ElectoralDistricts", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralDistrictSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("EligibleVoters")
                        .HasColumnType("int");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.Property<int?>("RegisteredVoters")
                        .HasColumnType("int");

                    b.Property<int?>("SeatsAllocated")
                        .HasColumnType("int");

                    b.Property<long?>("SourceImportRowId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("StatisticsDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectoralDistrictId", "ElectionId", "StatisticsDate")
                        .IsUnique();

                    b.ToTable("ElectoralDistrictSnapshots", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectoralCommitteeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ListNumber")
                        .HasColumnType("int");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectoralCommitteeId");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.HasIndex("PartyId");

                    b.HasIndex("ElectoralDistrictId", "ListNumber");

                    b.ToTable("ElectoralLists", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Geography.ElectoralDistrictTerritory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("CoverageType")
                        .HasColumnType("int");

                    b.Property<Guid>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TerritorialUnitId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TerritorialUnitId");

                    b.HasIndex("ElectoralDistrictId", "TerritorialUnitId")
                        .IsUnique();

                    b.ToTable("ElectoralDistrictTerritories", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Geography.TerritorialUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ParentTerytCode")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("TerytCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TerytCode", "ValidFrom");

                    b.ToTable("TerritorialUnits", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ElectionYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PipelineKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("PrimarySourceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersedesBatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineKey")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("ImportBatches", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DataSourceType")
                        .HasColumnType("int");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FormatVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("LastProcessedRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("LogFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("RawImportCompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RawImportStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<int>("TransformedRows")
                        .HasColumnType("int");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogicalName");

                    b.HasIndex("ImportBatchId", "Sha256");

                    b.ToTable("ImportFiles", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("char(36)");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("Status", "NextRetryAt");

                    b.ToTable("ImportJobs", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DomainEntityId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DomainEntityType")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ImportFileId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("int");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransformedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ImportFileId", "Status");

                    b.HasIndex("ImportFileId", "SheetName", "RowNumber")
                        .IsUnique();

                    b.ToTable("ImportRows", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.TransformationError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("json");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("ImportRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRowId");

                    b.ToTable("TransformationErrors", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.ElectionMandateAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("AllocatedSeat")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("AllocationAnnouncedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("CandidacyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ElectoralListId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("MandateId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RankOnListByVotes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidacyId")
                        .IsUnique();

                    b.HasIndex("ElectoralDistrictId");

                    b.HasIndex("ElectoralListId");

                    b.HasIndex("MandateId");

                    b.HasIndex("PoliticianId");

                    b.HasIndex("ElectionId", "CandidacyId")
                        .IsUnique();

                    b.ToTable("ElectionMandateAllocations", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.LegislativeTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Body")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ConstituentSessionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DissolvedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("FoundingElectionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("TermNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("VoivodeshipTerritorialUnitId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FoundingElectionId");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.HasIndex("VoivodeshipTerritorialUnitId");

                    b.HasIndex("Body", "TermNumber");

                    b.ToTable("LegislativeTerms", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.Mandate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AcquisitionType")
                        .HasColumnType("int");

                    b.Property<int>("Body")
                        .HasColumnType("int");

                    b.Property<Guid?>("ElectoralCommitteeId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ElectoralListId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LegislativeTermId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OriginatingCandidacyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("OriginatingElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PredecessorMandateId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SuccessorPriorityOnList")
                        .HasColumnType("int");

                    b.Property<string>("TerminationNote")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("TerminationReason")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ElectoralCommitteeId");

                    b.HasIndex("ElectoralListId");

                    b.HasIndex("OriginatingCandidacyId");

                    b.HasIndex("OriginatingElectionId");

                    b.HasIndex("PredecessorMandateId");

                    b.HasIndex("ElectoralDistrictId", "LegislativeTermId");

                    b.HasIndex("PoliticianId", "ValidFrom");

                    b.HasIndex("LegislativeTermId", "Body", "ValidFrom", "ValidTo");

                    b.ToTable("Mandates", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.MandateEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DetailsJson")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<Guid>("MandateId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Reason")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RelatedMandateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SourceDocumentRef")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<long?>("SourceImportRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MandateId");

                    b.HasIndex("RelatedElectionId");

                    b.HasIndex("RelatedMandateId");

                    b.ToTable("MandateEvents", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mapping.ManualMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "SourceKey")
                        .IsUnique();

                    b.ToTable("ManualMappings", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Parties.ClubMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParliamentaryClubId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.HasIndex("ParliamentaryClubId", "PoliticianId", "ValidFrom");

                    b.ToTable("ClubMemberships", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Parties.ParliamentaryClub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Body")
                        .HasColumnType("int");

                    b.Property<Guid>("LegislativeTermId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("LegislativeTermId");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.ToTable("ParliamentaryClubs", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Parties.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.ToTable("Parties", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Parties.PartyAffiliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("PoliticianId", "PartyId", "ValidFrom");

                    b.ToTable("PartyAffiliations", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politicians.IdentityMatchCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("MatchedPoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<long?>("SourceImportRowId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchedPoliticianId");

                    b.HasIndex("PoliticianId");

                    b.ToTable("IdentityMatchCandidates", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politicians.Politician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PkwCandidateId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("PkwCandidateId");

                    b.ToTable("Politicians", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politicians.PoliticianAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AliasName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateOnly?>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedAlias");

                    b.HasIndex("PoliticianId");

                    b.ToTable("PoliticianAliases", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politicians.PoliticianMergeOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("SourcePoliticianId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TargetPoliticianId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SourcePoliticianId")
                        .IsUnique();

                    b.HasIndex("TargetPoliticianId");

                    b.ToTable("PoliticianMergeOverrides", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Results.DistrictTurnoutResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("BallotsIssued")
                        .HasColumnType("int");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("SourceImportRowId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TurnoutPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("VotesInvalid")
                        .HasColumnType("int");

                    b.Property<int?>("VotesValid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectoralDistrictId");

                    b.HasIndex("ElectionId", "ElectoralDistrictId")
                        .IsUnique();

                    b.ToTable("DistrictTurnoutResults", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Results.ElectoralListVoteResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectoralDistrictId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ElectoralListId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("SeatsWon")
                        .HasColumnType("int");

                    b.Property<long?>("SourceImportRowId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("VotePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("VotesReceived")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ElectoralDistrictId");

                    b.HasIndex("ElectoralListId", "ElectionId", "ElectoralDistrictId")
                        .IsUnique();

                    b.ToTable("ElectoralListVoteResults", "app");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Candidacies.Candidacy", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralCommittee", "ElectoralCommittee")
                        .WithMany()
                        .HasForeignKey("ElectoralCommitteeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany()
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralList", "ElectoralList")
                        .WithMany()
                        .HasForeignKey("ElectoralListId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("ElectoralCommittee");

                    b.Navigation("ElectoralDistrict");

                    b.Navigation("ElectoralList");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Candidacies.CandidacyVoteResult", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Candidacies.Candidacy", "Candidacy")
                        .WithOne("VoteResult")
                        .HasForeignKey("PoliticalPaths.Domain.Candidacies.CandidacyVoteResult", "CandidacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany()
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidacy");

                    b.Navigation("Election");

                    b.Navigation("ElectoralDistrict");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.Election", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Mandates.LegislativeTerm", "LegislativeTerm")
                        .WithMany()
                        .HasForeignKey("LegislativeTermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Mandates.LegislativeTerm", "ParentLegislativeTerm")
                        .WithMany()
                        .HasForeignKey("ParentLegislativeTermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Geography.TerritorialUnit", "VoivodeshipTerritorialUnit")
                        .WithMany()
                        .HasForeignKey("VoivodeshipTerritorialUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LegislativeTerm");

                    b.Navigation("ParentLegislativeTerm");

                    b.Navigation("VoivodeshipTerritorialUnit");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralCommittee", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany("Committees")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Parties.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Election");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralDistrict", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany("Districts")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralDistrictSnapshot", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany("Snapshots")
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("ElectoralDistrict");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralList", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany("Lists")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralCommittee", "ElectoralCommittee")
                        .WithMany("Lists")
                        .HasForeignKey("ElectoralCommitteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany("Lists")
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Parties.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Election");

                    b.Navigation("ElectoralCommittee");

                    b.Navigation("ElectoralDistrict");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Geography.ElectoralDistrictTerritory", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany("Territories")
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Geography.TerritorialUnit", "TerritorialUnit")
                        .WithMany("DistrictTerritories")
                        .HasForeignKey("TerritorialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ElectoralDistrict");

                    b.Navigation("TerritorialUnit");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportBatch", "ImportBatch")
                        .WithMany("Files")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportJob", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportBatch", "ImportBatch")
                        .WithMany("Jobs")
                        .HasForeignKey("ImportBatchId");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportFile", "ImportFile")
                        .WithMany("Rows")
                        .HasForeignKey("ImportFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportFile");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.TransformationError", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportRow", "ImportRow")
                        .WithMany("Errors")
                        .HasForeignKey("ImportRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.ElectionMandateAllocation", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Candidacies.Candidacy", "Candidacy")
                        .WithOne("MandateAllocation")
                        .HasForeignKey("PoliticalPaths.Domain.Mandates.ElectionMandateAllocation", "CandidacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany()
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralList", "ElectoralList")
                        .WithMany()
                        .HasForeignKey("ElectoralListId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Mandates.Mandate", "Mandate")
                        .WithMany()
                        .HasForeignKey("MandateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidacy");

                    b.Navigation("Election");

                    b.Navigation("ElectoralDistrict");

                    b.Navigation("ElectoralList");

                    b.Navigation("Mandate");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.LegislativeTerm", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "FoundingElection")
                        .WithMany()
                        .HasForeignKey("FoundingElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Geography.TerritorialUnit", "VoivodeshipTerritorialUnit")
                        .WithMany()
                        .HasForeignKey("VoivodeshipTerritorialUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FoundingElection");

                    b.Navigation("VoivodeshipTerritorialUnit");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.Mandate", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralCommittee", "ElectoralCommittee")
                        .WithMany()
                        .HasForeignKey("ElectoralCommitteeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany()
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralList", "ElectoralList")
                        .WithMany()
                        .HasForeignKey("ElectoralListId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Mandates.LegislativeTerm", "LegislativeTerm")
                        .WithMany("Mandates")
                        .HasForeignKey("LegislativeTermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Candidacies.Candidacy", "OriginatingCandidacy")
                        .WithMany()
                        .HasForeignKey("OriginatingCandidacyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "OriginatingElection")
                        .WithMany()
                        .HasForeignKey("OriginatingElectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Mandates.Mandate", "PredecessorMandate")
                        .WithMany("SuccessorMandates")
                        .HasForeignKey("PredecessorMandateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ElectoralCommittee");

                    b.Navigation("ElectoralDistrict");

                    b.Navigation("ElectoralList");

                    b.Navigation("LegislativeTerm");

                    b.Navigation("OriginatingCandidacy");

                    b.Navigation("OriginatingElection");

                    b.Navigation("Politician");

                    b.Navigation("PredecessorMandate");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.MandateEvent", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Mandates.Mandate", "Mandate")
                        .WithMany("Events")
                        .HasForeignKey("MandateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "RelatedElection")
                        .WithMany()
                        .HasForeignKey("RelatedElectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Mandates.Mandate", "RelatedMandate")
                        .WithMany()
                        .HasForeignKey("RelatedMandateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mandate");

                    b.Navigation("RelatedElection");

                    b.Navigation("RelatedMandate");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Parties.ClubMembership", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Parties.ParliamentaryClub", "ParliamentaryClub")
                        .WithMany("Memberships")
                        .HasForeignKey("ParliamentaryClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParliamentaryClub");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Parties.ParliamentaryClub", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Mandates.LegislativeTerm", "LegislativeTerm")
                        .WithMany()
                        .HasForeignKey("LegislativeTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegislativeTerm");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Parties.PartyAffiliation", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Parties.Party", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politicians.IdentityMatchCandidate", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "MatchedPolitician")
                        .WithMany()
                        .HasForeignKey("MatchedPoliticianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchedPolitician");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politicians.PoliticianAlias", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "Politician")
                        .WithMany("Aliases")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politicians.PoliticianMergeOverride", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "SourcePolitician")
                        .WithMany()
                        .HasForeignKey("SourcePoliticianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Politicians.Politician", "TargetPolitician")
                        .WithMany()
                        .HasForeignKey("TargetPoliticianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourcePolitician");

                    b.Navigation("TargetPolitician");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Results.DistrictTurnoutResult", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany()
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("ElectoralDistrict");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Results.ElectoralListVoteResult", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Elections.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralDistrict", "ElectoralDistrict")
                        .WithMany()
                        .HasForeignKey("ElectoralDistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Elections.ElectoralList", "ElectoralList")
                        .WithMany()
                        .HasForeignKey("ElectoralListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("ElectoralDistrict");

                    b.Navigation("ElectoralList");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Candidacies.Candidacy", b =>
                {
                    b.Navigation("MandateAllocation");

                    b.Navigation("VoteResult");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.Election", b =>
                {
                    b.Navigation("Committees");

                    b.Navigation("Districts");

                    b.Navigation("Lists");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralCommittee", b =>
                {
                    b.Navigation("Lists");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Elections.ElectoralDistrict", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("Snapshots");

                    b.Navigation("Territories");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Geography.TerritorialUnit", b =>
                {
                    b.Navigation("DistrictTerritories");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportBatch", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.LegislativeTerm", b =>
                {
                    b.Navigation("Mandates");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Mandates.Mandate", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("SuccessorMandates");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Parties.ParliamentaryClub", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politicians.Politician", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
