<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoliticalPaths.Application\PoliticalPaths.Application.csproj" />
    <ProjectReference Include="..\PoliticalPaths.Domain\PoliticalPaths.Domain.csproj" />
  </ItemGroup>

</Project>
