// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliticalPaths.Infrastructure.Persistence;

#nullable disable

namespace PoliticalPaths.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809194917_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.Partia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataZakonczeniaDzialalnosci")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZalozenia")
                        .HasColumnType("date");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Skrot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Partia");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.PartiaCzlonkostwo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PartiaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WyboryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PartiaId");

                    b.HasIndex("PolitykId");

                    b.HasIndex("WyboryId");

                    b.ToTable("PartieCzlonkostwa");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ElectionYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PipelineKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PrimarySourceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersedesBatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineKey")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataSourceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FormatVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("LastProcessedRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("LogFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("LogicalNames")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("RawImportCompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RawImportStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<int>("TransformedRows")
                        .HasColumnType("int");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId", "Sha256");

                    b.ToTable("ImportFiles", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DomainEntityId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DomainEntityType")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ImportFileId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("int");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransformedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ImportFileId", "Status");

                    b.HasIndex("ImportFileId", "SheetName", "RowNumber")
                        .IsUnique();

                    b.ToTable("ImportRows", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.TransformationError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("json");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("ImportRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRowId");

                    b.ToTable("TransformationErrors", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.Mandat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataDo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataOd")
                        .HasColumnType("date");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StartWyborczyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TypObjecia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolitykId");

                    b.HasIndex("StartWyborczyId");

                    b.ToTable("Mandaty", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.ZdarzenieMandatowe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DataZdarzenia")
                        .HasColumnType("date");

                    b.Property<string>("DokumentReferencyjny")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("MandatId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MandatId");

                    b.HasIndex("PolitykId");

                    b.ToTable("ZdarzeniaMandatowe", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politycy.Polityk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataUrodzenia")
                        .HasColumnType("date");

                    b.Property<string>("DrugieImie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InformacjeDodatkowe")
                        .HasColumnType("longtext");

                    b.Property<string>("MiejsceUrodzenia")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Politycy");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.StartyWyborcze.StartWyborczy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KomitetId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ListaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MiejsceZamieszkania")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumerNaLiscie")
                        .HasColumnType("int");

                    b.Property<Guid?>("PartiaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PopierajacaPartiaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WyboryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Wyksztalcenie")
                        .HasColumnType("longtext");

                    b.Property<Guid>("WynikiId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Zawod")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ListaId");

                    b.HasIndex("PolitykId");

                    b.HasIndex("WyboryId");

                    b.HasIndex("WynikiId");

                    b.ToTable("StartyWyborcze");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.StartyWyborcze.WynikiWyborow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CzyMandat")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LiczbaGlosow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WynikiWyborow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.KomitetWyborczy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Skrot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KomitetyWyborcze");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.ListaWyborcza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KomitetWyborczyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NumerListy")
                        .HasColumnType("int");

                    b.Property<Guid>("OkregId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WyboryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ListaWyborcza");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.OkregWyborczy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("NumerOkregu")
                        .HasColumnType("int");

                    b.Property<Guid>("RodzajWyborowId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("OkregWyborczy");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.RodzajeWyborow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Poziom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RodzajeWyborow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.SzczegolyOkregu", b =>
                {
                    b.Property<Guid>("OkregId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WyboryId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LiczbaKandydatow")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaList")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaMandatow")
                        .HasColumnType("int");

                    b.Property<int>("Mieszkancy")
                        .HasColumnType("int");

                    b.Property<int>("RokWyborow")
                        .HasColumnType("int");

                    b.Property<int>("Uprawnieni")
                        .HasColumnType("int");

                    b.HasKey("OkregId", "WyboryId");

                    b.HasIndex("WyboryId");

                    b.ToTable("SzczegolyOkregow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.Wybory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CzyPrzedterminowe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("DataOgloszenia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWyborow")
                        .HasColumnType("date");

                    b.Property<int>("Ordynacja")
                        .HasColumnType("int");

                    b.Property<Guid>("RodzajWyborowId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Tura")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RodzajWyborowId");

                    b.ToTable("Wybory");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.PartiaCzlonkostwo", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Formacje.Partia", null)
                        .WithMany("Czlonkostwa")
                        .HasForeignKey("PartiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Politycy.Polityk", null)
                        .WithMany("Czlonkostwa")
                        .HasForeignKey("PolitykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Wybory.Wybory", null)
                        .WithMany("Czlonkostwa")
                        .HasForeignKey("WyboryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportBatch", "ImportBatch")
                        .WithMany("Files")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportFile", "ImportFile")
                        .WithMany("Rows")
                        .HasForeignKey("ImportFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportFile");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.TransformationError", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportRow", "ImportRow")
                        .WithMany("Errors")
                        .HasForeignKey("ImportRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.Mandat", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Politycy.Polityk", "Polityk")
                        .WithMany("Mandaty")
                        .HasForeignKey("PolitykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.StartyWyborcze.StartWyborczy", "StartWyborczy")
                        .WithMany()
                        .HasForeignKey("StartWyborczyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Polityk");

                    b.Navigation("StartWyborczy");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.ZdarzenieMandatowe", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Kadencje.Mandat", "Mandat")
                        .WithMany("Zdarzenia")
                        .HasForeignKey("MandatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Politycy.Polityk", null)
                        .WithMany()
                        .HasForeignKey("PolitykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandat");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.StartyWyborcze.StartWyborczy", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Wybory.ListaWyborcza", "ListaWyborcza")
                        .WithMany()
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Politycy.Polityk", "Polityk")
                        .WithMany("StartyWyborcze")
                        .HasForeignKey("PolitykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Wybory.Wybory", "Wybory")
                        .WithMany()
                        .HasForeignKey("WyboryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.StartyWyborcze.WynikiWyborow", "Wyniki")
                        .WithMany()
                        .HasForeignKey("WynikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaWyborcza");

                    b.Navigation("Polityk");

                    b.Navigation("Wybory");

                    b.Navigation("Wyniki");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.SzczegolyOkregu", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Wybory.OkregWyborczy", "Okreg")
                        .WithMany("Ludnosc")
                        .HasForeignKey("OkregId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Wybory.Wybory", "Wybory")
                        .WithMany()
                        .HasForeignKey("WyboryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Okreg");

                    b.Navigation("Wybory");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.Wybory", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Wybory.RodzajeWyborow", "Rodzaj")
                        .WithMany("Wybory")
                        .HasForeignKey("RodzajWyborowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rodzaj");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.Partia", b =>
                {
                    b.Navigation("Czlonkostwa");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportBatch", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.Mandat", b =>
                {
                    b.Navigation("Zdarzenia");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politycy.Polityk", b =>
                {
                    b.Navigation("Czlonkostwa");

                    b.Navigation("Mandaty");

                    b.Navigation("StartyWyborcze");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.OkregWyborczy", b =>
                {
                    b.Navigation("Ludnosc");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.RodzajeWyborow", b =>
                {
                    b.Navigation("Wybory");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.Wybory", b =>
                {
                    b.Navigation("Czlonkostwa");
                });
#pragma warning restore 612, 618
        }
    }
}
