// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliticalPaths.Infrastructure.Persistence;

#nullable disable

namespace PoliticalPaths.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604132859_Inicjalna_PL")]
    partial class Inicjalna_PL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.Formacje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataZakonczeniaDzialalnosci")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZalozenia")
                        .HasColumnType("date");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Skrot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Formacje");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.Kluby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Skrot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kluby");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.KlubyCzlonkowstwo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataDolaczenia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataOdejscia")
                        .HasColumnType("date");

                    b.Property<Guid>("KlubId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Powod")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KlubyCzlonkowstwo");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Geografia.Teryt", b =>
                {
                    b.Property<string>("KodTeryt")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("KodNadrzedny")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Poziom")
                        .HasColumnType("int");

                    b.HasKey("KodTeryt");

                    b.ToTable("Teryt");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ElectionYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PipelineKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PrimarySourceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersedesBatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineKey")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataSourceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FormatVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("LastProcessedRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("LogFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("RawImportCompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RawImportStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<int>("TransformedRows")
                        .HasColumnType("int");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogicalName");

                    b.HasIndex("ImportBatchId", "Sha256");

                    b.ToTable("ImportFiles", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DomainEntityId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DomainEntityType")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ImportFileId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("int");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransformedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ImportFileId", "Status");

                    b.HasIndex("ImportFileId", "SheetName", "RowNumber")
                        .IsUnique();

                    b.ToTable("ImportRows", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.TransformationError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("json");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("ImportRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRowId");

                    b.ToTable("TransformationErrors", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.Kadencja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataRozpoczecia")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZakonczenia")
                        .HasColumnType("date");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kadencje");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.Mandat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataDo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataOd")
                        .HasColumnType("date");

                    b.Property<Guid>("KadencjaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mandaty");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politycy.Politycy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataUrodzenia")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InformacjeDodatkowe")
                        .HasColumnType("longtext");

                    b.Property<string>("MiejsceUrodzeniaKodTeryt")
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Wyksztalcenie")
                        .HasColumnType("longtext");

                    b.Property<string>("Zawod")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Politycy");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.StartyWyborcze.StartyWyborcze", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ListaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NumerNaLiscie")
                        .HasColumnType("int");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("StartyWyborcze");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.StartyWyborcze.WynikiWyborow", b =>
                {
                    b.Property<Guid>("StartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("LiczbaGlosow")
                        .HasColumnType("int");

                    b.HasKey("StartId");

                    b.ToTable("WynikiWyborow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.KomitetyWyborcze", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RodzajKomitetuId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Skrot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KomitetyWyborcze");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.ListaWyborcza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KomitetWyborczyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MapaWyborowId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NumerListy")
                        .HasColumnType("int");

                    b.Property<Guid>("OkregId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ListaWyborcza");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.LudnoscOkregow", b =>
                {
                    b.Property<Guid>("OkregId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RokWyborow")
                        .HasColumnType("int");

                    b.Property<int>("Mieszkancy")
                        .HasColumnType("int");

                    b.Property<int>("Uprawnieni")
                        .HasColumnType("int");

                    b.HasKey("OkregId", "RokWyborow");

                    b.ToTable("LudnoscOkregow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.MapaOkregow", b =>
                {
                    b.Property<string>("KodTeryt")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("OkregWyborczyId")
                        .HasColumnType("char(36)");

                    b.HasKey("KodTeryt", "OkregWyborczyId");

                    b.ToTable("MapaOkregow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.MapaWyborow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataOgloszenia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWyborow")
                        .HasColumnType("date");

                    b.Property<int>("Ordynacja")
                        .HasColumnType("int");

                    b.Property<Guid>("RodzajWyborowId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("MapaWyborow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.OkregWyborczy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("NumerOkregu")
                        .HasColumnType("int");

                    b.Property<Guid>("RodzajWyborowId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("OkregWyborczy");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.SlownikWyborow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SlownikWyborow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportBatch", "ImportBatch")
                        .WithMany("Files")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportFile", "ImportFile")
                        .WithMany("Rows")
                        .HasForeignKey("ImportFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportFile");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.TransformationError", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportRow", "ImportRow")
                        .WithMany("Errors")
                        .HasForeignKey("ImportRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportBatch", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
