// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliticalPaths.Infrastructure.Persistence;

#nullable disable

namespace PoliticalPaths.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.Partia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataZakonczeniaDzialalnosci")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataZalozenia")
                        .HasColumnType("date");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Skrot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Partia");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.PartiaCzlonkostwo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PartiaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WyboryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PartiaId");

                    b.HasIndex("PolitykId");

                    b.HasIndex("WyboryId");

                    b.ToTable("PartieCzlonkostwa");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ElectionYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("PipelineKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("PrimarySourceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SupersedesBatchId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PipelineKey")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataSourceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FormatVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("char(36)");

                    b.Property<long?>("LastProcessedRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("LogFilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("LogicalNames")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime?>("RawImportCompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RawImportStartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.Property<int>("TransformedRows")
                        .HasColumnType("int");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId", "Sha256");

                    b.ToTable("ImportFiles", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DomainEntityId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DomainEntityType")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ImportFileId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RowHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SheetIndex")
                        .HasColumnType("int");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransformedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ImportFileId", "Status");

                    b.HasIndex("ImportFileId", "SheetName", "RowNumber")
                        .IsUnique();

                    b.ToTable("ImportRows", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.TransformationError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("json");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long>("ImportRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportRowId");

                    b.ToTable("TransformationErrors", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.Mandat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("DataOd")
                        .HasColumnType("date");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StartWyborczyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TypObjecia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolitykId");

                    b.HasIndex("StartWyborczyId");

                    b.ToTable("Mandaty", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.ZdarzenieMandatowe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DataZdarzenia")
                        .HasColumnType("date");

                    b.Property<string>("DokumentReferencyjny")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("MandatId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Opis")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MandatId");

                    b.HasIndex("PolitykId");

                    b.ToTable("ZdarzeniaMandatowe", (string)null);
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Messaging.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Messaging.EmailCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("EmailCampaigns");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Messaging.EmailDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("EmailDeliveries");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("InboxMessages");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politycy.Polityk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("DataUrodzenia")
                        .HasColumnType("date");

                    b.Property<string>("DrugieImie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InformacjeDodatkowe")
                        .HasColumnType("longtext");

                    b.Property<string>("MiejsceUrodzenia")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Politycy");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.StartyWyborcze.StartWyborczy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KomitetId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ListaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MiejsceZamieszkania")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumerNaLiscie")
                        .HasColumnType("int");

                    b.Property<Guid?>("PartiaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PolitykId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PopierajacaPartiaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WyboryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Wyksztalcenie")
                        .HasColumnType("longtext");

                    b.Property<Guid>("WynikiId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Zawod")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ListaId");

                    b.HasIndex("PolitykId");

                    b.HasIndex("WyboryId");

                    b.HasIndex("WynikiId");

                    b.ToTable("StartyWyborcze");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.StartyWyborcze.WynikiWyborow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CzyMandat")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LiczbaGlosow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WynikiWyborow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.KomitetWyborczy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Skrot")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("KomitetyWyborcze");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.ListaWyborcza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("KomitetWyborczyId")
                        .HasColumnType("char(36)");

                    b.Property<int>("NumerListy")
                        .HasColumnType("int");

                    b.Property<Guid>("OkregId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WyboryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ListaWyborcza");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.OkregWyborczy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("NumerOkregu")
                        .HasColumnType("int");

                    b.Property<Guid>("RodzajWyborowId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("OkregWyborczy");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.RodzajeWyborow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Poziom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RodzajeWyborow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.SzczegolyOkregu", b =>
                {
                    b.Property<Guid>("OkregId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WyboryId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LiczbaKandydatow")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaList")
                        .HasColumnType("int");

                    b.Property<int>("LiczbaMandatow")
                        .HasColumnType("int");

                    b.Property<int?>("Mieszkancy")
                        .HasColumnType("int");

                    b.Property<int>("RokWyborow")
                        .HasColumnType("int");

                    b.Property<int>("Uprawnieni")
                        .HasColumnType("int");

                    b.HasKey("OkregId", "WyboryId");

                    b.HasIndex("WyboryId");

                    b.ToTable("SzczegolyOkregow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.Wybory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CzyPrzedterminowe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("DataOgloszenia")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataWyborow")
                        .HasColumnType("date");

                    b.Property<string>("Kadencja")
                        .HasColumnType("longtext");

                    b.Property<int>("Ordynacja")
                        .HasColumnType("int");

                    b.Property<Guid>("RodzajWyborowId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Tura")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RodzajWyborowId");

                    b.ToTable("Wybory");
                });

            modelBuilder.Entity("PoliticalPaths.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EmailNotificationsChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PoliticalPaths.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PoliticalPaths.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PoliticalPaths.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.PartiaCzlonkostwo", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Formacje.Partia", null)
                        .WithMany("Czlonkostwa")
                        .HasForeignKey("PartiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Politycy.Polityk", null)
                        .WithMany("Czlonkostwa")
                        .HasForeignKey("PolitykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Wybory.Wybory", null)
                        .WithMany("Czlonkostwa")
                        .HasForeignKey("WyboryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportBatch", "ImportBatch")
                        .WithMany("Files")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportFile", "ImportFile")
                        .WithMany("Rows")
                        .HasForeignKey("ImportFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportFile");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.TransformationError", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Imports.ImportRow", "ImportRow")
                        .WithMany("Errors")
                        .HasForeignKey("ImportRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportRow");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.Mandat", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Politycy.Polityk", "Polityk")
                        .WithMany("Mandaty")
                        .HasForeignKey("PolitykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.StartyWyborcze.StartWyborczy", "StartWyborczy")
                        .WithMany()
                        .HasForeignKey("StartWyborczyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Polityk");

                    b.Navigation("StartWyborczy");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.ZdarzenieMandatowe", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Kadencje.Mandat", "Mandat")
                        .WithMany("Zdarzenia")
                        .HasForeignKey("MandatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Politycy.Polityk", "Polityk")
                        .WithMany("ZdarzeniaMandatowe")
                        .HasForeignKey("PolitykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandat");

                    b.Navigation("Polityk");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Messaging.EmailDelivery", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Messaging.EmailCampaign", "Campaign")
                        .WithMany("Deliveries")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.StartyWyborcze.StartWyborczy", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Wybory.ListaWyborcza", "ListaWyborcza")
                        .WithMany()
                        .HasForeignKey("ListaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoliticalPaths.Domain.Politycy.Polityk", "Polityk")
                        .WithMany("StartyWyborcze")
                        .HasForeignKey("PolitykId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Wybory.Wybory", "Wybory")
                        .WithMany()
                        .HasForeignKey("WyboryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.StartyWyborcze.WynikiWyborow", "Wyniki")
                        .WithMany()
                        .HasForeignKey("WynikiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListaWyborcza");

                    b.Navigation("Polityk");

                    b.Navigation("Wybory");

                    b.Navigation("Wyniki");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.SzczegolyOkregu", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Wybory.OkregWyborczy", "Okreg")
                        .WithMany("Ludnosc")
                        .HasForeignKey("OkregId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoliticalPaths.Domain.Wybory.Wybory", "Wybory")
                        .WithMany()
                        .HasForeignKey("WyboryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Okreg");

                    b.Navigation("Wybory");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.Wybory", b =>
                {
                    b.HasOne("PoliticalPaths.Domain.Wybory.RodzajeWyborow", "Rodzaj")
                        .WithMany("Wybory")
                        .HasForeignKey("RodzajWyborowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rodzaj");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Formacje.Partia", b =>
                {
                    b.Navigation("Czlonkostwa");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportBatch", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportFile", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Imports.ImportRow", b =>
                {
                    b.Navigation("Errors");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Kadencje.Mandat", b =>
                {
                    b.Navigation("Zdarzenia");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Messaging.EmailCampaign", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Politycy.Polityk", b =>
                {
                    b.Navigation("Czlonkostwa");

                    b.Navigation("Mandaty");

                    b.Navigation("StartyWyborcze");

                    b.Navigation("ZdarzeniaMandatowe");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.OkregWyborczy", b =>
                {
                    b.Navigation("Ludnosc");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.RodzajeWyborow", b =>
                {
                    b.Navigation("Wybory");
                });

            modelBuilder.Entity("PoliticalPaths.Domain.Wybory.Wybory", b =>
                {
                    b.Navigation("Czlonkostwa");
                });
#pragma warning restore 612, 618
        }
    }
}
