<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PoliticalPaths.Application\PoliticalPaths.Application.csproj" />
    <ProjectReference Include="..\PoliticalPaths.Domain\PoliticalPaths.Domain.csproj" />
    <ProjectReference Include="..\PoliticalPaths.Shared\PoliticalPaths.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
