<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoliticalPaths.Infrastructure\PoliticalPaths.Infrastructure.csproj" />
    <ProjectReference Include="..\PoliticalPaths.Domain\PoliticalPaths.Domain.csproj" />
    <ProjectReference Include="..\PoliticalPaths.Importers.Raw\PoliticalPaths.Importers.Raw.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <Content Include="..\..\CHANGELOG.md" Link="CHANGELOG.md" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\source-data\file-mappings.json" Link="file-mappings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\config\rabbitmq.topology.json" Link="rabbitmq.topology.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
